# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Ter Sami spellchecker"
sjt = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Ter Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sjt = "TRANSLATE: A spellchecker for Ter Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sjt"

[windows]
system_product_code = "{17ACF34A-40E0-4289-849A-45F95F2FFA20}_is1"
legacy_product_codes = [
    { value = "319902AA-912C-43A9-AB0D-F0D945858FD7", kind = "nsis" },
    { value = "2A3ABFED-468B-4F90-8903-0B1416904375", kind = "nsis" }
]

[package.speller]
name = "Ter Sami"
version = "0.1.1"

[package.grammar]
name = "Ter Sami"
version = "0.1.0"

[package.tts-text-proc]
name = "Ter Sami"
version = "0.1.0"

[package.hyphenator]
name = "Ter Sami"
version = "0.1.0"
