template = "https://github.com/giellalt/template-lang-und"
rev_id = 261
template_sha = "eaa0621ef7403d653282fabf176060ed3c95ebf4"

[replacements]
__GLOTTOLOG_ID__ = "ters1235"
__REPO__ = "lang-sjt"
__UND2C__ = "sjt"
__UNDEFINED__ = "Ter Sami"
__UND__ = "sjt"
