template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "ters1235"
__REPO__ = "lang-sjt"
__UND2C__ = "sjt"
__UNDEFINED__ = "Ter Sami"
__UND__ = "sjt"
