template = "https://github.com/giellalt/template-lang-und"
rev_id = 263
template_sha = "1bc24707891f274cd9b2690b032d9864fa1205f5"

[replacements]
__GLOTTOLOG_ID__ = "ters1235"
__REPO__ = "lang-sjt"
__UND2C__ = "sjt"
__UNDEFINED__ = "Ter Sami"
__UND__ = "sjt"
